# HAL packages
PRODUCT_PACKAGES += android.hardware.gnss@1.0-impl-qti
PRODUCT_PACKAGES += android.hardware.gnss@1.0-service-qti
PRODUCT_PACKAGES += android.hardware.gnss@1.1-impl-qti
PRODUCT_PACKAGES += android.hardware.gnss@1.1-service-qti
PRODUCT_PACKAGES += android.hardware.gnss@2.0-impl-qti
PRODUCT_PACKAGES += android.hardware.gnss@2.0-service-qti
PRODUCT_PACKAGES += gps.conf
PRODUCT_PACKAGES += libloc_core
PRODUCT_PACKAGES += libgnss
PRODUCT_PACKAGES += liblocation_api
PRODUCT_PACKAGES += libgps.utils
PRODUCT_PACKAGES += libbatching
PRODUCT_PACKAGES += libgeofencing
